# Generated by Django 5.2.6 on 2025-09-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career1', models.CharField(max_length=100)),
                ('career2', models.CharField(max_length=100)),
                ('career3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education1', models.CharField(max_length=100)),
                ('education2', models.CharField(max_length=100)),
                ('education3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('telegram', models.URLField(max_length=100)),
                ('instagram', models.URLField(max_length=100)),
                ('facebook', models.URLField(max_length=100)),
                ('twitter', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service1', models.CharField(max_length=100)),
                ('service1img', models.ImageField(upload_to='services/img')),
                ('service2', models.CharField(max_length=100)),
                ('service2img', models.ImageField(upload_to='services/img')),
                ('service3', models.CharField(max_length=100)),
                ('service3img', models.ImageField(upload_to='services/img')),
                ('service4', models.CharField(max_length=100)),
                ('service4img', models.ImageField(upload_to='services/img')),
            ],
        ),
    ]
