# Generated by Django 5.2.6 on 2025-09-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_info_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education1company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='education1year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='education2company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='education2year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='education3company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='education3year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
