# Generated by Django 5.2.6 on 2025-09-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_education_education1company_education_education1year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education1detail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='education2detail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='education3detail',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
