# Generated by Django 5.2.6 on 2025-09-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_education_education1detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='education2',
        ),
        migrations.RemoveField(
            model_name='education',
            name='education2company',
        ),
        migrations.RemoveField(
            model_name='education',
            name='education2detail',
        ),
        migrations.RemoveField(
            model_name='education',
            name='education2year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='education3',
        ),
        migrations.RemoveField(
            model_name='education',
            name='education3company',
        ),
        migrations.RemoveField(
            model_name='education',
            name='education3detail',
        ),
        migrations.RemoveField(
            model_name='education',
            name='education3year',
        ),
    ]
