# Generated by Django 5.2.6 on 2025-09-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_remove_education_education2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='career2',
        ),
        migrations.RemoveField(
            model_name='career',
            name='career3',
        ),
    ]
