# Generated by Django 5.2.6 on 2025-09-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_remove_career_career2_remove_career_career3'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='deatil',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='within',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
