# Generated by Django 5.2.6 on 2025-09-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_career_company_career_deatil_career_within'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='service1img',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service2img',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service3',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service3img',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service4',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service4img',
        ),
    ]
