# Generated by Django 5.2.6 on 2025-09-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_rename_service1img_services_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='detail',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
