# Generated by Django 5.2.6 on 2025-09-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0010_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='opinion/img')),
                ('job', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
            ],
        ),
    ]
