# Generated by Django 5.2.6 on 2025-09-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0013_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
