# Generated by Django 5.2.6 on 2025-09-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0015_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
