# Generated by Django 5.2.6 on 2025-09-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0016_portfolio_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='detail',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
